allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
overrides:
  sharp: 0.35.4
  postcss: 8.5.28
  effect: 3.22.2
  deepmerge-ts: 8.0.2
