package com.recipebuddy.android
import android.content.Intent
import android.net.Uri
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.platform.LocalContext
import kotlinx.serialization.json.*
import java.time.LocalDate
import java.util.UUID
@Composable fun MealCommerceControls(state:BuddyState,vm:BuddyViewModel,from:String){
 val root=state.meals?:return;val kitchen=root["state"]!!.jsonObject;val needs=root["shopping"]!!.jsonObject.mealRows("needs");val context=LocalContext.current
 var acknowledgeIncoming by rememberSaveable{mutableStateOf(false)};var open by rememberSaveable{mutableStateOf(false)};var selected by rememberSaveable{mutableStateOf(listOf<String>())};var country by rememberSaveable{mutableStateOf("FR")};var location by rememberSaveable{mutableStateOf("")};var fulfilment by rememberSaveable{mutableStateOf("delivery")}
 Column{KitchenTextButton(onClick={open=!open}){Text(mealText("Buy online · Pro","Acheter en ligne · Pro"))};if(open){
 Text(mealText("Online selection is separate from purchased checkmarks. A prepared list is not an order. Incoming goods are not usable stock.","La sélection en ligne est distincte des achats cochés. Une liste préparée n’est pas une commande. Les produits attendus ne sont pas du stock disponible."))
 val incoming=kitchen.mealRows("baskets").filter{it.mealValue("status") in listOf("handoff-pending","retailer-handoff","manually-confirmed-order","partially-received")};if(incoming.isNotEmpty()){Text(mealText("Incoming items or uncertain retailer status. Review these orders before ordering again; unavailable as stock.","Produits attendus ou statut commerçant incertain. Vérifiez ces commandes avant de commander à nouveau ; stock non disponible."));incoming.forEach{b->Text(b.mealRows("items").joinToString{it.mealValue("name")}+" · "+b.mealValue("status"))};Row{Checkbox(acknowledgeIncoming,{acknowledgeIncoming=it});Text(mealText("I reviewed these orders and intend another list despite overlapping needs","J’ai vérifié ces commandes et souhaite une nouvelle liste malgré les besoins similaires"))}}
 MealChoice(mealText("Country","Pays"),listOf("FR" to "France","US" to mealText("United States","États-Unis")),country,{country=it});MealField(mealText("Service location · postcode","Lieu de service · code postal"),location,{location=it});MealChoice(mealText("Fulfilment","Réception"),listOf("delivery" to mealText("Delivery","Livraison"),"pickup" to mealText("Pickup","Retrait")),fulfilment,{fulfilment=it})
 Text(if(country=="FR")mealText("France checkout awaits approved retailer partner access. Manual shopping is available.","Le paiement en France attend un accès partenaire agréé. Les achats manuels sont disponibles.")else mealText("US: Instacart development handoff requires credentials. Review store, products, prices, fees, slots and purchase at the retailer. No location has been verified for Recipe Buddy.","États-Unis : le transfert Instacart de développement nécessite des identifiants. Vérifiez magasin, produits, prix, frais, créneau et achat chez le commerçant. Aucun lieu vérifié pour Recipe Buddy."))
 needs.forEach{n->val key=n.mealValue("name").lowercase().trim()+"|"+n.mealValue("unit");Row{Checkbox(selected.contains(key),{selected=if(it)selected+key else selected-key});Text(n.mealValue("name")+": "+n.mealValue("quantity",mealText("Unknown","Inconnue"))+" "+n.mealValue("unit"))}}
 KitchenButton(enabled=!state.busy&&selected.isNotEmpty()&&location.isNotBlank(),onClick={vm.mealChange("prepare-basket",buildJsonObject{put("id",UUID.randomUUID().toString());put("country",country);put("acknowledgeIncoming",acknowledgeIncoming);put("location",location);put("fulfilment",fulfilment);put("from",from);put("to",LocalDate.parse(from).plusDays(6).toString());put("selected",JsonArray(selected.map(::JsonPrimitive)));put("diners",JsonArray(emptyList()))})}){Text(mealText("Prepare selected list","Préparer la liste choisie"))}
 kitchen.mealRows("baskets").forEach{b->
 Text(b.mealValue("country")+" · "+b.mealValue("location"),style=MaterialTheme.typography.titleMedium);Text(when(b.mealValue("status")){"prepared"->mealText("Prepared list","Liste préparée");"retailer-handoff"->mealText("Retailer handoff · no order evidence","Transfert commerçant · aucune preuve de commande");"manually-confirmed-order"->mealText("Incoming · order reported by you","Attendu · commande déclarée par vous");"partially-received"->mealText("Partially received","Reçu partiellement");"received"->mealText("Received","Reçu");"cancelled"->mealText("Cancelled · stock unchanged","Annulé · stock inchangé");else->mealText("Handoff response unknown","Réponse du transfert inconnue")})
 b.mealRows("items").forEach{Text(it.mealValue("name")+": "+it.mealValue("quantity",mealText("Unknown","Inconnue"))+" "+it.mealValue("unit"))}
 Text(mealText("Exact products, package counts, prices, fees, slots and substitution controls are unavailable here. Review at the retailer; changed products need new label checks.","Produits exacts, emballages, prix, frais, créneaux et substitutions indisponibles ici. Vérifiez chez le commerçant et revérifiez les étiquettes des substitutions."))
 if(b.mealValue("provider")=="instacart"&&b.mealValue("status")=="prepared")KitchenOutlinedButton(enabled=!state.busy,onClick={vm.prepareMealHandoff(b.mealValue("id"))}){Text(mealText("Prepare retailer handoff · review required","Préparer le transfert · vérification requise"))}
 if(b.mealValue("url").isNotBlank())KitchenTextButton(onClick={context.startActivity(Intent(Intent.ACTION_VIEW,Uri.parse(b.mealValue("url"))))}){Text(mealText("Review and checkout at retailer","Vérifier et payer chez le commerçant"))}
 if(b.mealValue("provider")=="instacart")KitchenTextButton(onClick={context.startActivity(Intent(Intent.ACTION_VIEW,Uri.parse("https://www.instacart.com/help")))}){Text(mealText("Retailer tracking, cancellation and support","Suivi, annulation et aide du commerçant"))}
 (root["receiptChecks"] as? JsonObject)?.mealRows(b.mealValue("id"))?.forEach{item->val status=item["check"]!!.jsonObject.mealValue("status");Text(item.mealValue("name")+" · "+mealText("Current restriction check","Vérification actuelle des restrictions")+": "+when(status){"conflict"->mealText("Conflict","Conflit");"unresolved"->mealText("Unresolved","Non résolu");else->mealText("Not assessed","Non évalué")}+" · "+mealText("Health suitability not established","Adéquation médicale non établie"))}
 MealOrderReconcile(b,state,vm);MealOrderReceive(b,state,vm);HorizontalDivider()
 }
 }}
}
@Composable private fun MealOrderReconcile(b:JsonObject,state:BuddyState,vm:BuddyViewModel){
 var open by rememberSaveable(b.mealValue("id")){mutableStateOf(false)};var reference by rememberSaveable(b.mealValue("id")){mutableStateOf(b.mealValue("providerOrderId"))};var notes by rememberSaveable(b.mealValue("id")){mutableStateOf("")};var status by rememberSaveable(b.mealValue("id")){mutableStateOf("manually-confirmed-order")}
 KitchenTextButton(onClick={open=!open}){Text(mealText("Reconcile retailer order manually","Rapprocher la commande manuellement"))};if(open){Text(mealText("Use actual retailer confirmation. A redirect is not purchase evidence. Refund alone changes no stock.","Utilisez la confirmation réelle du commerçant. Un lien ouvert ne prouve pas l’achat. Un remboursement seul ne change pas le stock."));MealField(mealText("Retailer order reference","Référence de commande"),reference,{reference=it});MealField(mealText("Evidence / notes","Preuve / notes"),notes,{notes=it});MealChoice(mealText("Actual status","Statut réel"),listOf("manually-confirmed-order" to mealText("Order confirmed by you","Commande confirmée par vous"),"cancelled" to mealText("Cancelled / refunded","Annulé / remboursé"),"received" to mealText("Receipt completed","Réception terminée")),status,{status=it});KitchenButton(enabled=!state.busy&&notes.isNotBlank()&&(status!="manually-confirmed-order"||reference.isNotBlank()),onClick={vm.mealChange("reconcile-order",buildJsonObject{put("id",b.mealValue("id"));put("status",status);put("providerOrderId",reference);put("notes",notes)})}){Text(mealText("Save reported order status","Enregistrer le statut déclaré"))}}
}
@Composable private fun MealOrderReceive(b:JsonObject,state:BuddyState,vm:BuddyViewModel){
 var open by rememberSaveable(b.mealValue("id")){mutableStateOf(false)};var name by rememberSaveable(b.mealValue("id")){mutableStateOf("")};var quantity by rememberSaveable(b.mealValue("id")){mutableStateOf("")};var unit by rememberSaveable(b.mealValue("id")){mutableStateOf("g")};var label by rememberSaveable(b.mealValue("id")){mutableStateOf("")};var complete by rememberSaveable(b.mealValue("id")){mutableStateOf(false)};var receiptId by rememberSaveable(b.mealValue("id")){mutableStateOf(UUID.randomUUID().toString())}
 LaunchedEffect(b){if(b["receivedBatchIds"]?.jsonArray?.any{it.jsonPrimitive.content==receiptId}==true){name="";quantity="";receiptId=UUID.randomUUID().toString()}}
 KitchenTextButton(onClick={open=!open}){Text(mealText("Confirm actual receipt","Confirmer la réception réelle"))};if(open){Text(mealText("Enter each received product and amount, including substitutes. Missing/damaged goods add no stock. Check labels; cross-contact remains unknown.","Saisissez chaque produit et quantité reçus, substitutions comprises. Produits absents ou endommagés : aucun stock ajouté. Vérifiez les étiquettes, contamination croisée inconnue."));MealField(mealText("Actual product","Produit réel"),name,{name=it});MealField(mealText("Actual quantity","Quantité réelle"),quantity,{quantity=it});MealField(mealText("Unit","Unité"),unit,{unit=it});MealField(mealText("Composition & allergens","Composition et allergènes"),label,{label=it});Row{Checkbox(complete,{complete=it});Text(mealText("All actual receipt items recorded","Tous les produits reçus sont enregistrés"))};KitchenButton(enabled=!state.busy&&name.isNotBlank()&&quantity.toDoubleOrNull()?.let{it>0}==true,onClick={vm.mealChange("receive-order",buildJsonObject{put("id",receiptId);put("basketId",b.mealValue("id"));put("batch",buildJsonObject{put("id",receiptId);put("name",name);put("quantity",quantity.toDouble());put("unit",unit);put("label",label)});put("complete",complete);put("notes","Manual actual receipt")})}){Text(mealText("Add received stock once","Ajouter le stock reçu une fois"))};Text(mealText("For actual returns/discarding, correct the actual batch in Pantry. Refund alone changes no stock.","Pour un retour ou une mise au rebut réels, corrigez le lot dans Stock. Un remboursement seul ne modifie pas le stock."))}
}
