"use client";
import { useState } from "react";
import type { Kitchen } from "@/lib/meal-engine";
import { batchSchema } from "@/lib/meal-engine";
import type { GroceryBasket } from "@/lib/meal-commerce";
import {incomingItems} from "@/lib/meal-commerce";
import { useTranslation } from "./language-provider";
export function MealCommerce({state,kitchenId,version,needs,from,to,mutate,busy,reload,receiptChecks}:{state:Kitchen;kitchenId:string;version:number;needs:{name:string;unit:string;quantity:number|null}[];from:string;to:string;mutate:(a:string,d:unknown)=>Promise<boolean>;busy:boolean;reload:()=>Promise<void>;receiptChecks:Record<string,{id:string;name:string;check:{status:string}}[]>}){
 const {t,locale}=useTranslation();const [selected,setSelected]=useState<string[]>([]),[country,setCountry]=useState("FR"),[location,setLocation]=useState(""),[fulfilment,setFulfilment]=useState("delivery"),[error,setError]=useState(""),[acknowledgeIncoming,setAcknowledgeIncoming]=useState(false);const incoming=incomingItems(state.baskets??[]);
 return <details><summary>{t("Buy online · Pro")}</summary><p>{t("Online selection is separate from purchased checkmarks. A prepared list is not an order, and incoming goods are not usable pantry stock.")}</p>
 <div className="meal-fields"><label>{t("Country")}<select value={country} onChange={e=>setCountry(e.target.value)}><option value="FR">France</option><option value="US">United States</option></select></label><label>{t("Service location · postcode")}<input value={location} onChange={e=>setLocation(e.target.value)}/></label><label>{t("Fulfilment")}<select value={fulfilment} onChange={e=>setFulfilment(e.target.value)}><option value="delivery">{t("Delivery")}</option><option value="pickup">{t("Pickup")}</option></select></label></div>
 <p>{t(country==="FR"?"France: retailer checkout is awaiting approved partner access. Export/manual shopping remains available.":"US: Instacart development shopping-list handoff requires credentials. Store, products, prices, fees, slots and final purchase are reviewed at the retailer. No service location has been verified for Recipe Buddy.")}</p>
 {needs.map(n=>{const key=n.name.toLowerCase().trim()+"|"+n.unit;return <label key={key}><input type="checkbox" checked={selected.includes(key)} onChange={e=>setSelected(e.target.checked?[...selected,key]:selected.filter(id=>id!==key))}/>{n.name}: {n.quantity??t("Quantity unknown")} {n.unit}</label>})}
 {!!incoming.length&&<div className="meal-card"><strong>{locale==="fr"?"Produits attendus ou statut commerçant incertain":"Incoming items or uncertain retailer status"}</strong>{incoming.map((i,n)=><p key={n}>{i.name} · {t(i.status)} · {locale==="fr"?"Vérifiez la commande avant de commander à nouveau ; stock non disponible":"Review the order before ordering again; unavailable as stock"}</p>)}<label><input type="checkbox" checked={acknowledgeIncoming} onChange={e=>setAcknowledgeIncoming(e.target.checked)}/>{locale==="fr"?"J’ai vérifié ces commandes et souhaite une nouvelle liste malgré les besoins similaires":"I reviewed these orders and intend another list despite overlapping needs"}</label></div>}
 <button className="button secondary" disabled={busy||!selected.length||!location.trim()} onClick={()=>mutate("prepare-basket",{id:crypto.randomUUID(),country,location,fulfilment,from,to,selected,diners:[],acknowledgeIncoming})}>{t("Prepare selected list")}</button>
 {error&&<p role="alert">{t(error)}</p>}
 {(state.baskets??[]).map(b=><article className="meal-card" key={b.id}><h3>{b.country} · {b.location} · {t(b.fulfilment)}</h3><p>{t(b.status)} · {t(b.checkoutEvidence==="none"?"No order evidence":"Order status reported by you")}</p>{b.items.map((i,n)=><p key={n}>{i.name}: {i.quantity??t("Quantity unknown")} {i.unit}</p>)}
 <p>{t("Exact products, package counts, prices, fees, slots and substitution controls are unavailable here. Review them at the retailer; changed products need new label checks.")}</p>
 {b.provider==="instacart"&&b.status==="prepared"&&<button className="button secondary" disabled={busy} onClick={async()=>{setError("");try{const response=await fetch("/api/meals/handoff",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operationId:crypto.randomUUID(),kitchenId,baseVersion:version,id:b.id})});const data=await response.json();if(!response.ok)throw Error(data.error);await reload()}catch(e){setError((e as Error).message)}}}>{t("Prepare retailer handoff · review required")}</button>}
 {b.url&&<a className="button secondary" href={b.url} target="_blank" rel="noopener noreferrer">{t("Review products and checkout at retailer")}</a>}
 {b.provider==="instacart"&&<a href="https://www.instacart.com/help" target="_blank" rel="noopener noreferrer">{t("Retailer tracking, cancellation and support")}</a>}
 <OrderReconcile basket={b} mutate={mutate} busy={busy}/><OrderReceive basket={b} mutate={mutate} busy={busy}/>
 {(receiptChecks[b.id]??[]).map(item=><p key={item.id}>{item.name} · {locale==="fr"?"Vérification actuelle des restrictions":"Current restriction check"}: {t(item.check.status)} · {t("Health suitability is not established")}</p>)}
 </article>)}
 </details>;
}
function OrderReconcile({basket,mutate,busy}:{basket:GroceryBasket;mutate:(a:string,d:unknown)=>Promise<boolean>;busy:boolean}){
 const {t}=useTranslation();const [reference,setReference]=useState(basket.providerOrderId),[notes,setNotes]=useState(""),[status,setStatus]=useState("manually-confirmed-order");return <details><summary>{t("Reconcile retailer order manually")}</summary><p>{t("Use your actual retailer confirmation. A redirect is not purchase evidence. Cancellation/refund does not remove pantry stock.")}</p><div className="meal-fields"><label>{t("Retailer order reference")}<input value={reference} onChange={e=>setReference(e.target.value)}/></label><label>{t("Evidence / notes")}<input value={notes} onChange={e=>setNotes(e.target.value)}/></label><label>{t("Actual status")}<select value={status} onChange={e=>setStatus(e.target.value)}>{["manually-confirmed-order","cancelled","received"].map(s=><option key={s} value={s}>{t(s)}</option>)}</select></label></div><button className="button secondary" disabled={busy||!notes.trim()||(status==="manually-confirmed-order"&&!reference.trim())} onClick={()=>mutate("reconcile-order",{id:basket.id,status,providerOrderId:reference,notes})}>{t("Save reported order status")}</button></details>;
}
function OrderReceive({basket,mutate,busy}:{basket:GroceryBasket;mutate:(a:string,d:unknown)=>Promise<boolean>;busy:boolean}){
 const {t}=useTranslation();const [name,setName]=useState(""),[quantity,setQuantity]=useState(""),[unit,setUnit]=useState("g"),[label,setLabel]=useState(""),[brand,setBrand]=useState(""),[complete,setComplete]=useState(false),[receiptId,setReceiptId]=useState<string|null>(null);
 return <details><summary>{t("Confirm actual receipt")}</summary><p>{t("Enter each actual received product and amount, including substitutions or weighted quantities. Missing/damaged goods create no stock. Labels do not certify cross-contact safety.")}</p><div className="meal-fields"><label>{t("Actual product")}<input value={name} onChange={e=>{setName(e.target.value);setReceiptId(null)}}/></label><label>{t("Actual quantity")}<input type="number" min="0.001" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>{t("Unit")}<input value={unit} onChange={e=>setUnit(e.target.value)}/></label><label>{t("Brand / variant")}<input value={brand} onChange={e=>setBrand(e.target.value)}/></label><label>{t("Composition & allergens")}<textarea value={label} onChange={e=>setLabel(e.target.value)}/></label></div><label><input type="checkbox" checked={complete} onChange={e=>setComplete(e.target.checked)}/>{t("All actual receipt items have now been recorded")}</label><button className="button secondary" disabled={busy||!name.trim()||!(Number(quantity)>0)} onClick={async()=>{const id=receiptId??crypto.randomUUID();setReceiptId(id);if(await mutate("receive-order",{id,basketId:basket.id,batch:batchSchema.parse({id,name,quantity:Number(quantity),unit,label,brand}),complete,notes:"Manual actual receipt"})){setName("");setQuantity("");setReceiptId(null)}}}>{t("Add received stock once")}</button><p>{t("For physically returned/discarded goods, use a stock correction for the actual batch. A refund alone changes no stock.")}</p></details>;
}
