'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Plus, Sparkles, Trash2, Save } from 'lucide-react';
import { recipeSchema, type RecipeInput, type RecipeView } from '@/lib/validation';
import { request } from '@/lib/client';
import { RecipePhotoInput } from './recipe-photo-input';
const blank: RecipeInput = { imageUrl: '', title: '', servings: 2, altTitle: '', vibe: 'cozy', ingredients: [{ name: '', quantity: '', unit: '' }], steps: [''] };
export function RecipeForm({ initial }: { initial?: RecipeView }) {
  const [photoBusy, setPhotoBusy] = useState(false);
  const router = useRouter(); const [form, setForm] = useState<RecipeInput>(initial || blank);
  const [raw, setRaw] = useState(''), [error, setError] = useState(''), [roast, setRoast] = useState(''), [busy, setBusy] = useState<'parse' | 'save' | null>(null);
  async function parse() {
    setBusy('parse'); setError('');
    try { const recipe = await request<RecipeInput & { roastLine: string }>('/api/recipes/parse', 'POST', { text: raw }); setForm(recipe); setRoast(recipe.roastLine); }
    catch (e) { setError(e instanceof Error ? e.message : 'Parsing failed. Add your recipe manually below.'); }
    finally { setBusy(null); }
  }
  async function save(e: React.FormEvent) {
    e.preventDefault(); setError(''); const parsed = recipeSchema.safeParse(form);
    if (!parsed.success) { setError(parsed.error.issues[0].message); return; }
    setBusy('save');
    try { const result = await request<{ id?: string }>(initial ? `/api/recipes/${initial.id}` : '/api/recipes', initial ? 'PUT' : 'POST', parsed.data); router.push(`/recipes/${initial?.id || result.id}`); router.refresh(); }
    catch (e) { setError(e instanceof Error ? e.message : 'Could not save. Please try again.'); }
    finally { setBusy(null); }
  }
  return <div className="editor"><Link href={initial ? `/recipes/${initial.id}` : '/recipes'} className="back-link"><ArrowLeft size={16} />Back to {initial ? 'recipe' : 'recipes'}</Link><div className="page-heading"><div><span className="eyebrow">A LITTLE SOMETHING DELICIOUS</span><h1>{initial ? 'Tweak the masterpiece.' : 'What’s cooking, chef?'}</h1><p>{initial ? 'Great recipes evolve. So do our opinions on cilantro.' : 'Write it down, or let your sous-chef do the typing.'}</p></div></div>
    {!initial && <section className="parse-panel"><h2><Sparkles size={20} /> A little kitchen magic</h2><p>Paste recipe text or a public HTTPS URL. We’ll sort out the ingredients and steps.</p><label className="sr-only" htmlFor="raw">Recipe text or URL</label><textarea id="raw" rows={4} value={raw} onChange={e => setRaw(e.target.value)} maxLength={16000} placeholder="That recipe you’ve had open in a tab for three weeks…" disabled={!!busy || photoBusy} /><div className="parse-bottom"><small>AI can get things wrong. Give the result a quick taste test.</small><button className="button primary" onClick={parse} disabled={!!busy || raw.trim().length < 10}><Sparkles size={16} />{busy === 'parse' ? 'Chef is reading…' : 'Parse recipe'}</button></div></section>}
    <form onSubmit={save}><fieldset disabled={!!busy} className="form-panel"><div className="section-label">01 <h2>The basics</h2></div><label>Recipe title<input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} maxLength={160} required placeholder="e.g. Sunday’s one-pot tomato pasta" /></label>{roast && <p className="speech">🧑‍🍳 {roast}</p>}<div className="form-row"><label>Silly subtitle <span className="optional">(optional)</span><input value={form.altTitle} onChange={e => setForm({ ...form, altTitle: e.target.value })} maxLength={180} placeholder="Carbs with main character energy" /></label><label>Servings<input type="number" min={1} max={100} required value={form.servings} onChange={e => setForm({ ...form, servings: Number(e.target.value) })} /></label><label>The vibe<select value={form.vibe} onChange={e => setForm({ ...form, vibe: e.target.value as RecipeInput['vibe'] })}>{['cozy', 'lazy', 'fancy', 'chaotic'].map(v => <option key={v}>{v}</option>)}</select></label></div>
    <RecipePhotoInput value={form.imageUrl} onChange={imageUrl => setForm(current => ({ ...current, imageUrl }))} onBusy={setPhotoBusy} /><div className="section-label">02 <h2>The good stuff</h2></div><div className="ingredient-head"><span>Ingredient</span><span>Quantity</span><span>Unit</span><span /></div>{form.ingredients.map((item, i) => <div className="ingredient-row" key={i}>{(['name', 'quantity', 'unit'] as const).map(key => <input key={key} aria-label={`Ingredient ${i + 1} ${key}`} placeholder={key === 'name' ? 'Cherry tomatoes' : key === 'quantity' ? '2' : 'cups'} required={key === 'name'} maxLength={key === 'name' ? 120 : 40} value={item[key]} onChange={e => setForm({ ...form, ingredients: form.ingredients.map((x, n) => n === i ? { ...x, [key]: e.target.value } : x) })} />)}<button type="button" className="icon-button" aria-label={`Remove ingredient ${i + 1}`} disabled={form.ingredients.length === 1} onClick={() => setForm({ ...form, ingredients: form.ingredients.filter((_, n) => n !== i) })}><Trash2 size={17} /></button></div>)}<button type="button" className="text-button" disabled={form.ingredients.length >= 100} onClick={() => setForm({ ...form, ingredients: [...form.ingredients, { name: '', quantity: '', unit: '' }] })}><Plus size={16} />Add ingredient</button>
    <div className="section-label">03 <h2>Make it happen</h2></div>{form.steps.map((step, i) => <div className="step-row" key={i}><span>{String(i + 1).padStart(2, '0')}</span><textarea aria-label={`Step ${i + 1}`} required maxLength={2000} rows={2} placeholder="First, put on your favorite playlist…" value={step} onChange={e => setForm({ ...form, steps: form.steps.map((x, n) => n === i ? e.target.value : x) })} /><button type="button" className="icon-button" aria-label={`Remove step ${i + 1}`} disabled={form.steps.length === 1} onClick={() => setForm({ ...form, steps: form.steps.filter((_, n) => n !== i) })}><Trash2 size={17} /></button></div>)}<button type="button" className="text-button" disabled={form.steps.length >= 80} onClick={() => setForm({ ...form, steps: [...form.steps, ''] })}><Plus size={16} />Add step</button></fieldset>{error && <p className="error" role="alert">{error}</p>}<div className="form-actions"><Link href="/recipes" className="button secondary">Cancel</Link><button className="button primary" disabled={!!busy || photoBusy}><Save size={17} />{busy === 'save' ? 'Saving your masterpiece…' : 'Save recipe'}</button></div></form></div>;
}
