import {mkdir,writeFile} from "node:fs/promises";
import {coverageManifest,checkMeal} from "../src/lib/meal-health";
import {profileSchema} from "../src/lib/meal-engine";
import {assessDaily,intakeSignature,recordedEstimate,recordedNutritionSchema,nutritionTargetSchema} from "../src/lib/meal-daily-nutrition";
async function main(){
 const scenarios=[{condition:"allergies",allergies:["milk"],ingredients:[{name:"whey",quantity:"10",unit:"g"}]},{condition:"coeliac",coeliac:true,ingredients:[{name:"barley",quantity:"10",unit:"g"}]},{condition:"pregnancy and gestational diabetes",pregnancy:true,diabetes:"gestational",ingredients:[{name:"rice",quantity:"100",unit:"g"}]},{condition:"child with multiple allergies",ageBand:"child",caregiverAuthorized:true,allergies:["egg","sesame"],ingredients:[{name:"tahini",quantity:"10",unit:"g"}]}];
 const cases=scenarios.map(s=>{const profile=profileSchema.parse({id:"review",name:"Review case",country:"FR",ageBand:"adult",consent:true,allergies:[],...s});return {scenario:s.condition,inputs:s,actual:checkMeal(s.ingredients,[profile]),reviewerVerdict:null,reviewer:null,reviewDate:null};});
 const evidence=recordedNutritionSchema.parse({portion:"TEST ONLY labelled portion",source:"Synthetic review fixture, not real food evidence",confirmed:true,values:{energyKcal:2000,carbohydrateG:200,proteinG:90,fatG:80,sodiumG:null,saltG:null}});
 const entry={id:"review-food",personId:"review",date:"2026-10-03",amount:null,approximate:false,nutritionEvidence:evidence,estimate:recordedEstimate(evidence)};
 const target=nutritionTargetSchema.parse({nutrient:"energyKcal",minimum:1800,maximum:2200,kind:"clinician-prescribed",source:"TEST ONLY prescription reference",issued:"2026-10-01",reviewDate:"2026-10-10",clinicianConfirmed:true});
 const dailyCases=[{scenario:"Unconfirmed diary",actual:assessDaily([entry],[target],undefined,entry.date)},{scenario:"Confirmed energy, unknown sodium and salt",actual:assessDaily([entry],[target],{confirmed:true,signature:intakeSignature([entry])},entry.date)},{scenario:"Added unknown snack invalidates confirmation",actual:assessDaily([entry,{...entry,id:"unknown-snack",nutritionEvidence:undefined,estimate:null}],[target],{confirmed:true,signature:intakeSignature([entry])},entry.date)}].map(c=>({...c,reviewerVerdict:null,reviewer:null,reviewDate:null}));
 await mkdir("test-results/meals",{recursive:true});await writeFile("test-results/meals/health-review-packet.json",JSON.stringify({manifest:coverageManifest,cases,dailyCases,instructions:"A qualified reviewer must evaluate source applicability, required evidence, clinical combinations and actual implementation. This packet does not activate any capability. Do not replace null review fields with inferred approval."},null,2));
}void main();
