import assert from 'node:assert/strict';
import { PrismaClient, type User } from '@prisma/client';
import { hash } from 'bcryptjs';
import { SignJWT } from 'jose';
import { randomUUID } from 'node:crypto';
import { opaqueToken, tokenHash } from '../src/lib/native-crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import sharp from 'sharp';
import { analyzeIngredients } from '../src/lib/native-vision';

// Deliberately impossible to run against the user's production database.
const dbUrl = new URL(process.env.DATABASE_URL!);
assert.equal(dbUrl.hostname, '127.0.0.1'); assert.equal(dbUrl.port, '55432');
assert.equal(dbUrl.pathname, '/recipe_buddy_test'); assert.equal(process.env.GROQ_API_KEY, '');
assert.equal(process.env.NEXTAUTH_URL, 'http://localhost:3002');
const db = new PrismaClient(); const base = 'http://127.0.0.1:3002';
const reports: string[] = [];
const ingredient = (name: string, quantity = '', unit = '') => ({ name, quantity, unit });
type Session = { accessToken: string; refreshToken: string; userId: string };
async function request(path: string, method = 'GET', data?: unknown, session?: Session, expected = 200) {
  const result = await fetch(base + path, { method, headers: { ...(session ? { Authorization: `Bearer ${session.accessToken}` } : {}), ...(method !== 'GET' ? { 'Content-Type': 'application/json' } : {}) },
    ...(method !== 'GET' ? { body: JSON.stringify(data ?? {}) } : {}) });
  const value = await result.json(); assert.equal(result.status, expected, `${method} ${path}: ${JSON.stringify(value)}`); return value;
}
async function check(name: string, fn: () => Promise<void>) { await fn(); reports.push(name); console.log(`PASS ${name}`); }
async function login(email: string) { return request('/api/native/auth/login', 'POST', { email, password: 'NativeTestOnly-2026' }) as Promise<Session>; }
async function main() {
  const users: User[] = [];
  for (const letter of ['a', 'b', 'c']) users.push(await db.user.upsert({ where: { email: `native-${letter}@example.test` }, update: { roastEnabled: false },
    create: { email: `native-${letter}@example.test`, username: `Test Kitchen ${letter.toUpperCase()}`, hashedPassword: await hash('NativeTestOnly-2026', 12), roastEnabled: false } }));
  await db.rateLimit.deleteMany();
  await db.recipe.deleteMany({ where: { userId: { in: users.map(u => u.id) } } });
  await db.friendship.deleteMany({ where: { OR: [{ userAId: { in: users.map(u => u.id) } }, { userBId: { in: users.map(u => u.id) } }] } });
  const [a, b, c] = await Promise.all(users.map(u => login(u.email)));
  await Promise.all([a, b, c].map(s => request('/api/native/v1/terms', 'POST', { version: '2026-10-03', accepted: true }, s)));
  assert.equal(a.userId, users[0].id);
  const input = { title: 'Test recipe · Tomato, egg & rice', servings: 2, ingredients: [ingredient('tomato', '2'), ingredient('egg', '2'), ingredient('rice', '200', 'g')], steps: ['Prepare the tomatoes and beat the eggs.', 'Cook rice for 10 minutes. Check texture, then stir in tomatoes and egg.'], vibe: 'cozy' };
  const owned = await request('/api/native/v1/recipes', 'POST', input, a, 201);
  const unshared = await request('/api/native/v1/recipes', 'POST', { ...input, title: 'Test recipe · Private rice' }, c, 201);
  const extra = await request('/api/native/v1/recipes', 'POST', { ...input, title: 'Test recipe · Rice with onion', ingredients: [...input.ingredients, ingredient('onion', '1')] }, a, 201);
  await check('existing password identity, CRUD and explicit native/browser boundary', async () => {
    await request(`/api/native/v1/recipes/${owned.id}`, 'GET', undefined, b, 404);
    await request(`/api/native/v1/recipes/${owned.id}`, 'PUT', input, b, 404);
    await request('/api/recipes', 'GET', undefined, a, 401);
    await request(`/api/native/v1/recipes/${owned.id}`, 'PUT', { ...input, title: input.title + ' · edited' }, a);
    const read = await request(`/api/native/v1/recipes/${owned.id}`, 'GET', undefined, a); assert.ok(read.title.endsWith('edited')); assert.equal(read.owned, true);
    const home = await request('/api/native/v1/home', 'GET', undefined, a);
    assert.equal(home.me.id, a.userId); assert.ok(home.recipes.items.some((r: { id: string }) => r.id === owned.id));
    const otherHome = await request('/api/native/v1/home', 'GET', undefined, b);
    assert.ok(!otherHome.recipes.items.some((r: { id: string }) => r.id === owned.id));
    await request(`/api/native/v1/recipes/${owned.id}/coach`, 'POST', { step: 0, language: 'en', servings: 2 }, b, 404);
    const evil = await fetch(base + '/api/native/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: 'https://evil.test' }, body: JSON.stringify({ email: users[0].email, password: 'NativeTestOnly-2026' }) }); assert.equal(evil.status, 403);
  });
  await check('offline sync commits once, preserves versions/dates and rechecks access', async () => {
    const entityId = 'c' + randomUUID().replaceAll('-', '').slice(0, 24);
    const op = { operationId: randomUUID(), path: 'recipes', method: 'POST', payload: JSON.stringify({ ...input, title: 'Offline saved recipe' }), entityId, occurredAt: new Date().toISOString() };
    const results = await Promise.all([request('/api/native/v1/sync', 'POST', op, a), request('/api/native/v1/sync', 'POST', op, a)]);
    assert.equal(results[0].recipe.id, entityId); assert.deepEqual(results[0], results[1]);
    assert.equal(await db.recipe.count({ where: { id: entityId } }), 1);
    await request('/api/native/v1/sync', 'POST', { ...op, payload: JSON.stringify(input) }, a, 409);
    const read = await request(`/api/native/v1/recipes/${entityId}`, 'GET', undefined, a);
    const edit = { operationId: randomUUID(), path: `recipes/${entityId}`, method: 'PUT', payload: JSON.stringify({ ...input, title: 'My offline edit' }), baseVersion: read.updatedAt, occurredAt: new Date().toISOString() };
    await db.recipe.update({ where: { id: entityId }, data: { title: 'A newer web edit' } });
    await request('/api/native/v1/sync', 'POST', edit, a, 409);
    assert.equal(await db.nativeSyncReceipt.count({ where: { userId: a.userId, operationId: edit.operationId } }), 0);
    const latest = await request(`/api/native/v1/recipes/${entityId}`, 'GET', undefined, a);
    const savedEdit = await request('/api/native/v1/sync', 'POST', { ...edit, baseVersion: latest.updatedAt }, a);
    assert.equal(savedEdit.recipe.title, 'My offline edit');
    const nextEdit = { ...edit, operationId: randomUUID(), baseVersion: 'after:' + edit.operationId, payload: JSON.stringify({ ...input, title: 'A second queued edit' }) };
    await request('/api/native/v1/sync', 'POST', nextEdit, a);
    const contribution = { operationId: randomUUID(), path: `recipes/${entityId}/discussion`, method: 'POST', payload: JSON.stringify({ kind: 'comment', text: 'Saved while offline', takeId: null }), entityId: 'c' + randomUUID().replaceAll('-', '').slice(0, 24), occurredAt: new Date().toISOString() };
    await request('/api/native/v1/sync', 'POST', contribution, b, 404);
    assert.equal(await db.recipeComment.count({ where: { id: contribution.entityId } }), 0);
    await request('/api/native/v1/sync', 'POST', contribution, a);
    await request('/api/native/v1/sync', 'POST', contribution, a);
    assert.equal(await db.recipeComment.count({ where: { id: contribution.entityId } }), 1);
    const date = new Date(Date.now() - 86400_000).toISOString();
    await request('/api/native/v1/sync', 'POST', { operationId: randomUUID(), path: `recipes/${entityId}/cook`, method: 'POST', payload: '{}', occurredAt: date }, a);
    assert.equal((await db.cookedLog.findFirstOrThrow({ where: { recipeId: entityId } })).date.toISOString().slice(0, 10), date.slice(0, 10));
    const kitchen = { operationId: randomUUID(), path: 'kitchen-state', method: 'PUT', payload: JSON.stringify({ kind: 'shopping', id: 'sync-test', payload: JSON.stringify({ id: 'sync-test', name: 'Tomato', amount: '2', checked: true }) }), occurredAt: new Date().toISOString() };
    await request('/api/native/v1/sync', 'POST', kitchen, a);
    await request('/api/native/v1/sync', 'POST', { ...kitchen, operationId: randomUUID(), payload: '{invalid' }, a, 400);
    await request('/api/native/v1/sync', 'POST', { ...kitchen, operationId: randomUUID(), payload: JSON.stringify({ kind: 'shopping', id: 'invalid', payload: '{invalid' }) }, a, 400);
    const state = await request('/api/native/v1/kitchen-state', 'GET', undefined, a); assert.ok(state.some((r: { id: string }) => r.id === 'sync-test'));
    assert.ok(!(await request('/api/native/v1/kitchen-state', 'GET', undefined, b)).some((r: { id: string }) => r.id === 'sync-test'));
    await request('/api/native/v1/sync', 'POST', { ...kitchen, operationId: randomUUID(), path: 'pro/verify' }, a, 400);
    await request(`/api/native/v1/recipes/${entityId}`, 'DELETE', {}, a);
  });
  await check('bounded private-name suggestions and Pro voice authorization', async () => {
    const person = await db.user.findUniqueOrThrow({ where: { id: b.userId } });
    const results = await request('/api/native/v1/chef-search?name=' + encodeURIComponent(person.username!), 'GET', undefined, a);
    assert.ok(results.some((row: { id: string }) => row.id === b.userId));
    assert.ok(results.every((row: Record<string, unknown>) => Object.keys(row).every(key => ['id', 'username'].includes(key))));
    const suggestions = await request('/api/native/v1/chef-search?name=tes', 'GET', undefined, a);
    assert.ok(suggestions.some((row: { id: string }) => row.id === b.userId));
    assert.ok(suggestions.length <= 5 && suggestions.every((row: { id: string; username: string }) => row.id !== a.userId && row.username.toLowerCase().startsWith('tes')));
    await request('/api/native/v1/chef-search?name=tes', 'GET', undefined, undefined, 401);
    assert.deepEqual(await request('/api/native/v1/chef-search?name=te%25', 'GET', undefined, a), []);
    assert.deepEqual(await request('/api/native/v1/chef-search?name=te_', 'GET', undefined, a), []);
    await request('/api/native/v1/chef-search?name=na', 'GET', undefined, a, 400);
    await request('/api/native/v1/chef-search?name=chef@example.test', 'GET', undefined, a, 400);
    await request('/api/native/v1/voice-command', 'POST', { text: 'next step', language: 'en', isPro: true }, a, 402);
    await db.nativeKitchenState.deleteMany({ where: { userId: a.userId, kind: 'shopping', id: 'versioned-test' } });
    const item = { kind: 'shopping', id: 'versioned-test', payload: JSON.stringify({ id: 'versioned-test', name: 'Rice', amount: '2', checked: false }) };
    const op = { operationId: randomUUID(), path: 'kitchen-state', method: 'PUT', payload: JSON.stringify(item), baseVersion: 'missing', occurredAt: new Date().toISOString() };
    const first = await request('/api/native/v1/sync', 'POST', op, a);
    assert.ok(first.kitchenVersion);
    await request('/api/native/v1/sync', 'POST', { ...op, operationId: randomUUID() }, a, 409);
    await request('/api/native/v1/sync', 'POST', { ...op, operationId: randomUUID(), baseVersion: 'after:' + op.operationId }, a);
  });
  await check('Pro gates resist client spoofing and one free roast persists across edits and steps', async () => {
    const pro = await request('/api/native/v1/pro', 'GET', undefined, a);
    assert.equal(pro.active, false); assert.equal(pro.billingReady, false);
    await request('/api/native/v1/pro/verify', 'POST', { purchaseToken: 'invented-purchase-token', active: true }, a, 503);
    const coach = { step: 0, language: 'en', servings: 2, roast: true };
    await request(`/api/native/v1/recipes/${owned.id}/coach`, 'POST', { ...coach, isPro: true }, a, 402);
    await request(`/api/native/v1/recipes/${owned.id}/chef-roast`, 'POST', { ...coach, variation: 1 }, a, 402);
    const saved = 'Your tomato chopping technique looks like the knife won the argument.';
    await db.chefRoast.create({ data: { userId: a.userId, recipeId: owned.id, step: 0, language: 'en', text: saved } });
    const first = await request(`/api/native/v1/recipes/${owned.id}/chef-roast`, 'POST', { ...coach, step: 1, language: 'fr' }, a);
    assert.equal(first.roast, saved); assert.equal(first.step, 0); assert.equal(first.language, 'en');
    await request(`/api/native/v1/recipes/${owned.id}`, 'PUT', { ...input, title: 'Edited without resetting the allowance' }, a);
    assert.equal((await request(`/api/native/v1/recipes/${owned.id}/chef-roast`, 'POST', coach, a)).roast, saved);
    await request(`/api/native/v1/recipes/${unshared.id}/chef-roast`, 'POST', coach, a, 404);
    await request(`/api/native/v1/recipes/${extra.id}/chef-roast`, 'POST', coach, a, 503);
    assert.equal(await db.chefRoast.count({ where: { recipeId: extra.id, userId: a.userId } }), 0);
    await request('/api/native/billing-notifications', 'POST', { message: { data: 'spoof', messageId: '1' } }, undefined, 503);
  });
  await check('single-use invite concurrency, replay, expiry, self-invite and regeneration', async () => {
    const invite = await request('/api/native/v1/invites', 'POST', {}, a); const token = new URL(invite.url).pathname.split('/').pop()!;
    await request(`/api/native/v1/invites/${token}`, 'POST', {}, a, 400);
    const responses = await Promise.all([b, c].map(s => fetch(base + `/api/native/v1/invites/${token}`, { method: 'POST', headers: { Authorization: `Bearer ${s.accessToken}`, 'Content-Type': 'application/json' }, body: '{}' })));
    assert.deepEqual(responses.map(r => r.status).sort(), [200, 409]);
    const winner = responses[0].status === 200 ? b : c;
    await request(`/api/native/v1/invites/${token}`, 'POST', {}, winner);
    // Create the A/B connection deterministically for share tests if C won.
    const pair = [a.userId, b.userId].sort(); await db.friendship.upsert({ where: { userAId_userBId: { userAId: pair[0], userBId: pair[1] } }, create: { userAId: pair[0], userBId: pair[1], requesterId: a.userId, acceptedAt: new Date() }, update: { acceptedAt: new Date() } });
    const old = await request('/api/native/v1/invites', 'POST', {}, a); const oldToken = new URL(old.url).pathname.split('/').pop()!;
    await request('/api/native/v1/invites', 'POST', {}, a); await request(`/api/native/v1/invites/${oldToken}`, 'GET', undefined, b, 410);
    const expired = opaqueToken(); await db.friendInvite.create({ data: { hash: tokenHash(expired), inviterId: a.userId, expiresAt: new Date(0) } });
    await request(`/api/native/v1/invites/${expired}`, 'POST', {}, b, 410);
  });
  await check('web parity: apron scoring, twists, threaded comments, native search and chef privacy', async () => {
    await request(`/api/native/v1/recipes/${owned.id}/shares`, 'POST', { recipientId: b.userId }, a);
    const chefBefore = (await request('/api/native/v1/me', 'GET', undefined, a)).chef;
    const reviewPath = `/api/native/v1/recipes/${owned.id}/reviews`;
    await request(reviewPath, 'PUT', { rating: 5, text: 'Great texture.' }, a, 403);
    await request(reviewPath, 'PUT', { rating: 6 }, b, 400);
    await request(reviewPath, 'PUT', { rating: 4, text: 'Great texture.' }, b);
    await request(reviewPath, 'PUT', { rating: 5, text: 'Updated after cooking.' }, b);
    const updated = (await request('/api/native/v1/me', 'GET', undefined, a)).chef;
    assert.equal(updated.points, chefBefore.points + 10); assert.equal(updated.receivedAprons, 5); assert.equal(updated.reviewCount, 1);
    assert.equal((await request(reviewPath, 'GET', undefined, a)).reviews.length, 1);
    const discussionPath = `/api/native/v1/recipes/${owned.id}/discussion`;
    await request(discussionPath, 'POST', { kind: 'take', title: 'Crispier tomatoes', type: 'technique', change: 'Sauté tomatoes separately.', ingredient: 'tomato', reason: 'Keep the rice fluffy.' }, b, 201);
    await request(discussionPath, 'POST', { kind: 'take', title: 'Wrong ingredient', change: 'Test', ingredient: 'not in recipe' }, b, 400);
    const take = (await request(discussionPath, 'GET', undefined, a)).takes[0];
    await request(discussionPath, 'POST', { kind: 'comment', text: 'Thanks for the tip.', takeId: take.id }, a, 201);
    await request(discussionPath, 'POST', { kind: 'comment', text: 'Works nicely.' }, b, 201);
    const community = await request(`/api/native/v1/recipes/${owned.id}/community`, 'GET', undefined, b);
    assert.equal(community.recipeId, owned.id); assert.equal(community.discussion.comments.length, 2);
    await request(`/api/native/v1/recipes/${unshared.id}/community`, 'GET', undefined, a, 404);
    const reply = community.discussion.comments.find((v: any) => v.takeId === take.id);
    await request(discussionPath, 'DELETE', { kind: 'comment', id: reply.id }, b, 404);
    await request(discussionPath, 'DELETE', { kind: 'take', id: take.id }, a);
    assert.equal((await request(discussionPath, 'GET', undefined, b)).comments.length, 1);
    const profile = await request(`/api/native/v1/chefs/${a.userId}`, 'GET', undefined, b);
    assert.deepEqual(profile.recipes.map((r: any) => r.id), [owned.id]); assert.equal(profile.chef.points, updated.points);
    await request(`/api/native/v1/chefs/${b.userId}`, 'GET', undefined, c, 404);
    const results = await request('/api/native/v1/search?q=beat', 'GET', undefined, b);
    assert.ok(results.some((r: any) => r.id === owned.id)); assert.ok(!results.some((r: any) => r.id === unshared.id));
    const me = await request('/api/native/v1/me', 'GET', undefined, a); assert.equal(me.levels.length, 7); assert.equal(me.week.days.length, 7);
    assert.deepEqual((await request('/api/native/v1/translate', 'POST', { locale: 'fr', texts: ['200 g', '10'] }, a)).translations, ['200 g', '10']);
    await request(`/api/native/v1/recipes/${owned.id}/translations`, 'POST', {}, b, 404);
    await request(`/api/native/v1/recipes/${owned.id}/roast`, 'POST', {}, a, 402);
    const original = await db.recipe.findUniqueOrThrow({ where: { id: owned.id } });
    const translations = original.translations as { en?: Record<string, string>; fr?: Record<string, string> };
    await db.recipe.update({ where: { id: owned.id }, data: { translations: { ...translations, en: translations.en ?? {}, fr: { ...translations.fr, [original.title]: 'Recette native tomate riz' }, version: 2, pending: true } } });
    assert.ok((await request('/api/native/v1/recipes?q=Recette', 'GET', undefined, a)).items.some((r: any) => r.id === owned.id));
    await request(reviewPath, 'DELETE', {}, b); assert.equal((await request('/api/native/v1/me', 'GET', undefined, a)).chef.points, chefBefore.points);
    await request(`/api/native/v1/recipes/${owned.id}/shares`, 'DELETE', { recipientId: b.userId }, a);
    await request(discussionPath, 'POST', { kind: 'comment', text: 'After revocation' }, b, 404);
    await request(reviewPath, 'PUT', { rating: 4 }, b, 403);
    assert.equal((await request(`/api/native/v1/chefs/${a.userId}`, 'GET', undefined, b)).recipes.length, 0);
    assert.equal((await request('/api/native/v1/search?q=beat', 'GET', undefined, b)).length, 0);
    await request(discussionPath, 'DELETE', { kind: 'comment', id: community.discussion.comments.find((v: any) => !v.takeId).id }, a);
  });
  await check('share-only matching, quantity uncertainty, revoke and friendship cascade', async () => {
    await request(`/api/native/v1/recipes/${owned.id}/shares`, 'POST', { recipientId: b.userId }, a);
    const shared = await request(`/api/native/v1/recipes/${owned.id}`, 'GET', undefined, b); assert.equal(shared.owned, false);
    await request(`/api/native/v1/recipes/${owned.id}`, 'DELETE', {}, b, 404);
    const matches = await request('/api/native/v1/matches', 'POST', { ingredients: [ingredient('tomates'), ingredient('œufs'), ingredient('riz')] }, a);
    assert.equal(matches[0].recipe.id, owned.id); assert.equal(matches[0].quantityCaveat, 'unknown'); assert.ok(!matches.some((m: any) => m.recipe.id === unshared.id)); assert.equal(matches.find((m: any) => m.recipe.id === extra.id).missing.length, 1);
    const before = await request('/api/native/v1/matches', 'POST', { ingredients: [ingredient('tomato'), ingredient('egg'), ingredient('rice')] }, b); assert.ok(before.some((m: any) => m.recipe.id === owned.id));
    await request(`/api/native/v1/recipes/${owned.id}/shares`, 'DELETE', { recipientId: b.userId }, a);
    const after = await request('/api/native/v1/matches', 'POST', { ingredients: [ingredient('tomato'), ingredient('egg'), ingredient('rice')] }, b); assert.ok(!after.some((m: any) => m.recipe.id === owned.id));
    await request(`/api/native/v1/recipes/${owned.id}/shares`, 'POST', { recipientId: b.userId }, a);
    const friendship = await db.friendship.findFirstOrThrow({ where: { userAId: [a.userId, b.userId].sort()[0], userBId: [a.userId, b.userId].sort()[1] } });
    await request(`/api/native/v1/friends/${friendship.id}`, 'DELETE', {}, a); await request(`/api/native/v1/recipes/${owned.id}`, 'GET', undefined, b, 404);
  });
  await check('cooked UTC date is idempotent and shopping preserves fractions/units', async () => {
    await request(`/api/native/v1/recipes/${owned.id}/cook`, 'POST', {}, a); await request(`/api/native/v1/recipes/${owned.id}/cook`, 'POST', {}, a);
    assert.equal(await db.cookedLog.count({ where: { userId: a.userId, recipeId: owned.id } }), 1);
    const recipe = await request('/api/native/v1/recipes', 'POST', { ...input, title: 'Test recipe · Fractions', ingredients: [ingredient('rice', '1 1/2', 'cups'), ingredient('rice', '1/2', 'cup'), ingredient('rice', '20', 'g'), ingredient('salt', 'to taste')] }, a, 201);
    const list = await request('/api/native/v1/shopping-list', 'POST', { recipeIds: [recipe.id] }, a); assert.deepEqual(list.find((i: any) => i.name === 'rice').amounts, ['2 cup', '20 g']);
    await request('/api/native/v1/shopping-list', 'POST', { recipeIds: [unshared.id] }, a, 404);
  });
  await check('refresh rotation, replay family revocation, expiry and logout', async () => {
    const original = await login(users[1].email), rotated = await request('/api/native/auth/refresh', 'POST', { refreshToken: original.refreshToken });
    await request('/api/native/v1/me', 'GET', undefined, rotated);
    await request('/api/native/auth/refresh', 'POST', { refreshToken: original.refreshToken }, undefined, 401);
    await request('/api/native/v1/me', 'GET', undefined, rotated, 401);
    const fresh = await login(users[1].email); await request('/api/native/auth/logout', 'POST', { refreshToken: fresh.refreshToken }, fresh);
    await request('/api/native/v1/me', 'GET', undefined, fresh, 401);
    const expired = await new SignJWT({ sid: 'test' }).setSubject(b.userId).setProtectedHeader({ alg: 'HS256' }).setIssuer('recipe-buddy-native').setAudience('recipe-buddy-app').setExpirationTime(1).sign(new TextEncoder().encode(process.env.NATIVE_SESSION_SECRET));
    await request('/api/native/v1/me', 'GET', undefined, { ...b, accessToken: expired }, 401);
    const concurrent = await login(users[2].email);
    const replay = await Promise.all([1, 2].map(() => fetch(base + '/api/native/auth/refresh', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ refreshToken: concurrent.refreshToken }) })));
    assert.deepEqual(replay.map(r => r.status).sort(), [200, 401]);
  });
  await check('PKCE state, single-use code and expired exchange', async () => {
    const verifier = opaqueToken(), state = opaqueToken(), code = opaqueToken();
    const attempt = await db.nativeAuthAttempt.create({ data: { state, challenge: tokenHash(verifier), redirect: 'recipebuddy://auth', codeHash: tokenHash(code), userId: a.userId, expiresAt: new Date(Date.now() + 60_000) } });
    await request('/api/native/auth/exchange', 'POST', { code, verifier: opaqueToken(), state }, undefined, 401);
    await request('/api/native/auth/exchange', 'POST', { code, verifier, state: opaqueToken() }, undefined, 401);
    const issued = await request('/api/native/auth/exchange', 'POST', { code, verifier, state }); assert.equal(issued.userId, a.userId);
    await request('/api/native/auth/exchange', 'POST', { code, verifier, state }, undefined, 401);
    const staleCode = opaqueToken(); await db.nativeAuthAttempt.update({ where: { id: attempt.id }, data: { codeHash: tokenHash(staleCode), consumedAt: null, expiresAt: new Date(0) } });
    await request('/api/native/auth/exchange', 'POST', { code: staleCode, verifier, state }, undefined, 401);
  });
  await check('disabled vision is explicit, JSON/upload bounds remain intact', async () => {
    await request('/api/native/v1/analyze', 'POST', { requestId: randomUUID(), locale: 'en', image: 'data:image/jpeg;base64,YQ==' }, a, 402);
    await request('/api/native/v1/matches', 'POST', { padding: 'x'.repeat(450_001) }, a, 413);
  });
  await check('FIXTURE vision validates output, caches per account and prevents duplicate/quota billing', async () => {
    const image = 'data:image/jpeg;base64,' + (await sharp({ create: { width: 20, height: 20, channels: 3, background: '#faf9f5' } }).jpeg().toBuffer()).toString('base64');
    const input = { requestId: randomUUID(), locale: 'en', image };
    process.env.VISION_ENABLED = 'true'; process.env.VISION_MODEL = 'fixture-only'; process.env.GROQ_API_KEY = 'fixture-no-real-call'; process.env.VISION_DAILY_QUOTA = '1';
    let calls = 0;
    const provider = { async recognize() { calls++; await new Promise(r => setTimeout(r, 30)); return { suggestions: [{ canonical: 'tomato', label: 'tomato', quantity: '', unit: '', uncertain: true }] }; } };
    const first = await analyzeIngredients(a.userId, input, provider);
    assert.equal(first.suggestions[0].uncertain, true);
    assert.deepEqual(await analyzeIngredients(a.userId, input, provider), first); assert.equal(calls, 1);
    await assert.rejects(analyzeIngredients(a.userId, { ...input, locale: 'fr' }, provider), (e: any) => e.status === 409);
    await assert.rejects(analyzeIngredients(a.userId, { ...input, requestId: randomUUID() }, provider), (e: any) => e.status === 429); assert.equal(calls, 1);
    const concurrent = await Promise.allSettled([1, 2].map(() => analyzeIngredients(b.userId, input, provider)));
    assert.equal(concurrent.filter(r => r.status === 'fulfilled').length, 1); assert.equal(calls, 2);
    const malformed = { async recognize() { return { suggestions: [{ canonical: '<bad>', label: 'invalid' }] }; } };
    await assert.rejects(analyzeIngredients(c.userId, { ...input, requestId: randomUUID() }, malformed), (e: any) => e.status === 502);
    process.env.VISION_ENABLED = 'false'; process.env.GROQ_API_KEY = '';
  });
  await check('blocking revokes shares, prevents reinvites and limits reporting to accessible content', async () => {
    const pair = [a.userId, b.userId].sort();
    await db.friendship.upsert({ where: { userAId_userBId: { userAId: pair[0], userBId: pair[1] } }, create: { userAId: pair[0], userBId: pair[1], requesterId: a.userId, acceptedAt: new Date() }, update: { acceptedAt: new Date() } });
    await request(`/api/native/v1/recipes/${owned.id}/shares`, 'POST', { recipientId: b.userId }, a);
    await request('/api/native/v1/reports', 'POST', { recipeId: owned.id, reason: 'Fixture report only: test unsafe content' }, b);
    await request('/api/native/v1/reports', 'POST', { recipeId: unshared.id, reason: 'Cannot report inaccessible content' }, b, 404);
    await request('/api/native/v1/blocks', 'POST', { chefId: a.userId }, b);
    await request(`/api/native/v1/recipes/${owned.id}`, 'GET', undefined, b, 404);
    assert.equal((await request('/api/native/v1/shared-recipes', 'GET', undefined, b)).length, 0);
    const blockedHome = await request('/api/native/v1/home', 'GET', undefined, b);
    assert.equal(blockedHome.shared.length, 0); assert.ok(!blockedHome.friends.some((f: { friend: { id: string } }) => f.friend.id === a.userId));
    const fromA = await request('/api/native/v1/chef-search?name=tes', 'GET', undefined, a);
    const fromB = await request('/api/native/v1/chef-search?name=tes', 'GET', undefined, b);
    assert.ok(!fromA.some((row: { id: string }) => row.id === b.userId));
    assert.ok(!fromB.some((row: { id: string }) => row.id === a.userId));
    await request('/api/native/v1/friends', 'POST', { email: users[1].email }, a, 403);
    const invitation = await request('/api/native/v1/invites', 'POST', {}, a);
    await request('/api/native/v1/invites/' + new URL(invitation.url).pathname.split('/').pop(), 'POST', {}, b, 403);
    await request('/api/native/v1/blocks', 'DELETE', { chefId: a.userId }, b);
    await request('/api/native/v1/reports', 'POST', { recipeId: owned.id, reason: 'x' }, a, 400);
    await db.contentReport.deleteMany({ where: { reason: { startsWith: 'Fixture report only:' } } });
  });
  await check('terms gate, verified account deletion, cascade and stale session revocation', async () => {
    const email = 'native-delete@example.test';
    await db.user.deleteMany({ where: { email } });
    const user = await db.user.create({ data: { email, username: 'Deletion fixture only', hashedPassword: await hash('NativeTestOnly-2026', 12), roastEnabled: false } });
    const s = await login(email);
    await request('/api/native/v1/recipes', 'POST', input, s, 428);
    await request('/api/native/v1/terms', 'POST', { accepted: true, version: 'wrong' }, s, 400);
    await request('/api/native/v1/terms', 'POST', { accepted: true, version: '2026-10-03' }, s);
    const recipe = await request('/api/native/v1/recipes', 'POST', input, s, 201);
    await db.nativeAuthAttempt.create({ data: { userId: user.id, state: opaqueToken(), challenge: opaqueToken(), redirect: 'recipebuddy://auth', expiresAt: new Date(Date.now() + 60_000) } });
    await db.nativeScan.create({ data: { userId: user.id, key: tokenHash(user.id), digest: 'fixture', result: { suggestions: [] }, expiresAt: new Date(Date.now() + 60_000) } });
    await db.nativeSession.updateMany({ where: { userId: user.id }, data: { authenticatedAt: new Date(Date.now() - 600_000) } });
    await request('/api/native/v1/account', 'DELETE', { confirmation: 'DELETE' }, s, 403);
    await request('/api/native/v1/account', 'DELETE', { confirmation: 'DELETE', password: 'WrongPassword2026' }, s, 403);
    await request('/api/native/v1/account', 'DELETE', { confirmation: 'DELETE', password: 'NativeTestOnly-2026' }, s);
    assert.equal(await db.user.count({ where: { id: user.id } }), 0);
    assert.equal(await db.recipe.count({ where: { id: recipe.id } }), 0);
    assert.equal(await db.nativeSession.count({ where: { userId: user.id } }), 0);
    assert.equal(await db.nativeAuthAttempt.count({ where: { userId: user.id } }), 0);
    assert.equal(await db.nativeScan.count({ where: { userId: user.id } }), 0);
    await request('/api/native/v1/me', 'GET', undefined, s, 401);
    await request('/api/native/auth/refresh', 'POST', { refreshToken: s.refreshToken }, undefined, 401);
  });
  await mkdir('mobile/test-results', { recursive: true });
  await writeFile('mobile/test-results/integration.json', JSON.stringify({ database: 'local isolated Docker', providerCalls: 0, tests: reports, recipeId: owned.id }, null, 2));
  console.log(`${reports.length} integration groups passed; provider calls: 0`);
}
main().finally(() => db.$disconnect()).catch(error => { console.error(error.message); process.exitCode = 1; });
